[project]
name = "blatt-1"
version = "0.1.0"
description = "Optimierungsverfahren"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "gurobipy>=12.0.1",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
